version: '3.5'
services:
  k6:
    image: grafana/k6:latest
    volumes:
      - ./performance-test.js:/performance-test.js:ro
    command: ["run","/performance-test.js"]
    depends_on:
      - nginx
    restart: "no"